config/routes.rb
Resume::Application.routes.draw do
  resources :docs
  resources :users
  resources :user_sessions
  get "downloads/index"
  get "downloads/download"

  get 'download', to: 'downloads#index',       as: :download
  get 'login',    to: 'user_sessions#new',     as: :login
  get 'logout',   to: 'user_sessions#destroy', as: :logout
  
  #root :to => 'docs#index'
  root :to => 'user_sessions#new'
end

app/models/doc.rb
class Doc < ActiveRecord::Base
  scopify
  
  def document_file=( document_data )
    self.filename       = document_data.original_filename
    self.content_type   = document_data.content_type.chomp
    self.binary_content = document_data.read
  end
  
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  
  acts_as_authentic do |c|
    c.logged_in_timeout = 30.minutes
  end

  authenticates_many :user_sessions
  
  validates_presence_of :login, :password
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
    before_destroy :_reset_persistence_token
    before_create  :_reset_persistence_token
    
  logout_on_timeout true
  
  private
    def _reset_persistence_token
      record.reset_persistence_token!
    end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  include_all_helpers
  helper_method :current_user_session, :current_user, :admin_rights, :layout
  
# TODO: refactor logic
    def admin_rights
      if current_user
        if current_user.has_role? :admin
          return true
        else
          return false
        end
      else
        return false
      end
    end
  
    def _check_admin_rights
      unless admin_rights
        redirect_to_session_or_default root_url
      end
    end  
  
    def require_user
      unless current_user
        _set_return_location
        flash[:notice] = "Login needed to access this page."
        redirect_to new_user_session_url
        return false
      end
    end
    
    def current_user
      return @current_user if defined?(@current_user)
      @current_user = current_user_session && current_user_session.record
    end

    def current_user_session
      return @current_user_session if defined?(@current_user_session)
      @current_user_session = UserSession.find
    end
    
    def _set_return_location
      session[:return_to] = request.url
    end
    
    def redirect_to_session_or_default(default)
      #flash[:notice] = "Return_to: " + session[:return_to]
      redirect_to(session[:return_to] || default)
      session[:return_to] = nil
    end
    
    def layout
      if current_user_session
        if admin_rights
          #logger.info "----> application"
          "application"
        else
          #logger.info "----> application_client"
          "application_client"
        end
      else
        "login"
      end
    end
 end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :_check_admin_rights, 
            only: [:new, :edit, :create, :update, :destroy]
  before_action :require_user, only: [:download]
  before_action :_set_doc, only: [:show, :edit, :update, :destroy]
  helper_method :download, :layout
  layout :layout
  
  #TODO: selectable docs to be displayed in client section
  # GET /docs
  def index
    @docs = Doc.all
  end

  # GET /docs/1
  def show
  end

  # GET /docs/new
  def new
    @doc = Doc.new
  end

  # GET /docs/1/edit
  def edit
  end

  # POST /docs
  def create
    @doc = Doc.new(_doc_params)

    if @doc.save
      redirect_to @doc, notice: 'Document was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /docs/1
  def update
    if @doc.update(_doc_params)
      redirect_to @doc, notice: 'Document was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /docs/1
  def destroy
    @doc.destroy
    redirect_to docs_url, notice: 'Document was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def _set_doc
      @doc = Doc.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def _doc_params
      params.require(:doc).permit(:document_file, 
                                  :filename, 
                                  :description, 
                                  :binary_content, 
                                  :content_type)
    end
         
    def download(filename, filetype)
      send_file filename, type: filetype
    end
end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController
  helper DownloadsHelper
  
  def index
    @docs = Doc.all
  end
  
  def download
    doc = Doc.find(params[:id])
    send_data doc.binary_content, 
              filename: doc.filename, 
              type: doc.content_type 
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_action :require_user, only: [:destroy]
  
  layout "login"
  
  def new
    @user_session = UserSession.new
  end
  
  def create
    @user_session = UserSession.new(_user_params)
    if @user_session.save
      flash[:notice] = "Login success."
      #redirect_to_session_or_default account_url
      redirect_to docs_url
    else
      render :action => :new
    end
  end
  
  def destroy
    current_user_session.destroy
    flash[:notice] = "Logout success."
    redirect_to_session_or_default new_user_session_url
  end
  
  private
  def _user_params
    params.require(:user_session).permit(:login, :password)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :_check_admin_rights
  before_action :_set_user, only: [:show, :edit, :update, :destroy]
  
  layout "application"
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(_user_params)
      
    if params[:admin_rights] == "1"
      @user.add_role :admin
    end
    
    if @user.save
      flash[:notice] = "User " + @user.login + " created successfully."
      redirect_to root_url
    else
      render :action => "new"  
    end
  end
  
  def index
    @users = User.all
    @roles = Role.all
  end
  
  def show
    if current_user.has_role? :admin
      @user = User.find(params[:id])
    else
      @user = current_user
    end
  end


  def update
    respond_to do |format|
      if @user.update(_user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
    end
  end
  
  private
    def _set_user
      @user = User.find(params[:id])
    end
    
    def _user_params
      params.require(:user).permit(:login, 
                                   :password, 
                                   :password_confirmation, 
                                   :admin_rights)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/downloads_helper.rb
module DownloadsHelper
  
  def icon( doc )
    icon_elements = Hash.new
    
    case doc.content_type
      when "application/pdf"
        icon_elements = {
          icon: 'pdf.png',
          alt: 'Pdf' 
        }
      
      when "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
         icon_elements = {
          icon: 'docx.png',
          alt:  'docx' 
        }
        
      else
        icon_elements = {
          icon: 'default.png',
          alt:  'Default type'
        }
    end
    
    icon_elements[:size] = '64x64'        
    return icon_elements
  end
   
end

app/views/application/_flashes.html.erb
<div id="flash">
  <% flash.each do |key, value| -%>
    <div id="flash_<%= key %>"><%= value %></div>
  <% end -%>
</div>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/docs/_form.html.erb
<%= form_for(@doc) do |form| %>
  <table class="tables">  
    <tr>
      <td align="right"><%= form.label :description, "Document description" %></td>
      <td align="left"><%= form.text_field :description %></td>  
    </tr>
    </table>
      <%= form.file_field "document_file", class: "browse button" %> <%# NOTE: see model/doc.rb %>
  <%= form.submit "Upload", class: "button" %>
  
  <%= render "shared/error_messages", :target => @doc %>
<% end %>

app/views/docs/edit.html.erb
<h1>Editing doc</h1>

<%= render 'form' %>

<%= link_to 'Show', @doc %> |
<%= link_to 'Back', docs_path %>

app/views/docs/index.html.erb
<h1>Documents</h1>

<table class="tables">
  <thead>
    <tr>
      <th>Filename</th>
      <th>Description</th>
      <th>Content_type</th>
      <th>Owner</th>
    </tr>
  </thead>

  <tbody>
    <% @docs.each do |doc| %>
      <tr>
        <td><%= doc.filename %></td>
        <td><%= doc.description %></td>
        <td><%= doc.content_type %></td>
        <td><%= doc.owner %></td>
        <td><%#= doc.binary_content %></td>
        <td><%#= link_to 'Show', doc %></td>
        <td><%= link_to 'Edit', edit_doc_path(doc) %></td>
        <td><%= link_to 'Destroy', doc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doc', new_doc_path %>

app/views/docs/new.html.erb
<h1>New document</h1>

<%= render 'form' %>

<%= link_to 'Back', docs_path %>

app/views/docs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_doc_path(@doc) %> |
<%= link_to 'Back', docs_path %>

app/views/downloads/index.html.erb
<h1>Resume</h1>

<table class="tables">
  <tr class="table_row">
    <% @docs.each do |doc| %>
      <%#= doc.inspect %>
      <td>
        <%= link_to image_tag( icon(doc)[:icon],                               
                               alt: icon(doc)[:alt],
                               size: icon(doc)[:size], 
                               class:"icon" 
                             ),
                    downloads_download_url( id: doc ) %>
        <%= doc.description %>
      </td>
    <% end %>
  </tr> 
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <title><%= page_title %></title>
  <%= stylesheet_link_tag :application, :media => 'all' %>
  <%= csrf_meta_tags %>
</head>

<body class="body_application">

  <div class="header_paragraph">
    <img src="/assets/<insert an image here>" alt="<Insert a name here>" />
  </div>
  
  <div>
    <div class="empty_between_header_and_login">  </div>
    <div class="login_panel">
      <%= render template: "user_sessions/destroy" %>
    </div>
  </div>
  
  <div class="empty_between_panels">  
  </div>
  
  <div class="main_yield">
    <%= render 'flashes' -%>
    <%= yield %>
    <%= render 'javascript' %>
  </div>
  
  <div class="empty_between_main_and_footer">

  </div>

</body>
</html>

app/views/layouts/application_client.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <title><%= page_title %></title>
  <%= stylesheet_link_tag :application, :media => 'all' %>
  <%= csrf_meta_tags %>
</head>

<body class="body_application">

  <div class="header_paragraph">
    <img src="/assets/<insert an image here>" alt="<Insert a name here>" />
  </div>
  
  <div>
    <div class="empty_between_header_and_login">  </div>
    <div class="login_panel">
      <%= render template: "user_sessions/destroy" %>
    </div>
  </div>
  
  <div class="empty_between_panels">  
  </div>
  
  <div class="client_yield">
    <div class="client_index">
    <%= render template: "downloads/index" %>
    <%= render 'javascript' %>
    </div>

      <%= image_tag('<insert an image here>', size:"300x400")%>

  </div>
  
  <div class="empty_between_main_and_footer">
  </div>

  <div class="footer">
    <%=link_to image_tag('ruby.png',      size:"64x64", alt:"Ruby",      class:"icon"), "https://www.ruby-lang.org/en/" %>
    <%=link_to image_tag('rails.png',     size:"64x64", alt:'Rails',     class:"icon"), "http://rubyonrails.org/" %>
    <%=link_to image_tag('postgresql.gif',size:"110x64",alt:'PostGreSql',class:"icon"), "http://www.postgresql.org/" %>
    <%=link_to image_tag('linkedin.png',  size:"64x64", alt:'LinkedIn',  class:"icon"), "http://www.linkedin.com/pub/<insert a linkedin url>" %>
    <%=link_to image_tag('github.jpeg',   size:"64x64", alt:'GitHub',    class:"icon"), "https://www.github.com/cebericus" %>
    <div class="login_panel"><%= render 'flashes' -%></div>
  </div>

</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <title><%= page_title %></title>
  <%= stylesheet_link_tag :application, :media => 'all' %>
  <%= csrf_meta_tags %>
</head>

<body class="body_login">

  <div class="header_paragraph">
    <img src="/assets/<insert an image here>" alt="<Insert a name here>" />
  </div>
  
  <div>
    <div class="empty_between_header_and_login">  </div>
    <div class="login_panel">
      <%= yield %>
    </div>
  </div>
  
  <div class="empty_between_panels">  
  </div>
  
  <div class="main_yield">
    <%= render "shared/error_messages", :target => @user_session %>
    <%= render 'flashes' -%>
    <%= render 'javascript' %>
  </div>
       
</body>
</html>

app/views/shared/_error_messages.html.erb
<%# Example: <%= render "shared/error_messages", :target => @user %>

<% if target.errors.any? %>  
<div id="errors">  
  <h2>This transaction not complete because of <%= pluralize(target.errors.count, "error") %>.</h2>  
  <ul>  
  <% target.errors.full_messages.each do |msg| %>  
    <li><%= msg %></li>  
  <% end %>  
  </ul>  
</div>  
<% end %> 

app/views/shared/_form_table_factory.html.erb
<%# Example: <%= render "shared/error_messages", :target => @user %>

<% if target.errors.any? %>  
<div id="errors">  
  <h2>This transaction not complete because of <%= pluralize(target.errors.count, "error") %>.</h2>  
  <ul>  
  <% target.errors.full_messages.each do |msg| %>  
    <li><%= msg %></li>  
  <% end %>  
  </ul>  
</div>  
<% end %> 

app/views/user_sessions/destroy.html.erb
<%= form_tag( "/logout", method: "get", html: {class: "login_panel"} ) do %>  
  <table class="tables">
    <tr>
      <td><%= current_user.login.camelize + " @ " + current_user.current_login_ip + "   "  %></td>
      <td><%= button_tag(type: 'submit', class: 'button') do
              content_tag(:strong, 'Logout')
            end%>
      </td>  
    </tr>  
  </table>
<% end %> 

app/views/user_sessions/new.html.erb
<%= form_for @user_session do |form| %>  
  <table class="tables_panel">
    <tr>  
      <td><%= form.label :login, "Username" %></td>  
      <td><%= form.text_field :login %></td>
      </tr>
      <tr>  
      <td><%= form.label :password, "Password" %></td>  
      <td><%= form.password_field :password %></td>
      </tr>
      <tr> 
      <td><%= button_tag(type: 'submit', class: 'button') do
              content_tag(:strong, 'Login')
            end%>
      </td>  
    </tr>  
  </table>
<% end %> 

app/views/users/_user.html.erb
<%= form_for @user do |form| %>
  
  <table class="tables">  
    <tr>
      <td align="right"><%= form.label :login, "Username" %></td>  
      <td align="left"><%= form.text_field :login %></td>   
    </tr>
    <tr>
      <td align="right"><%= form.label :password, "Password" %></td>   
      <td align="left"><%= form.password_field :password %></td>   
    </tr>
    <tr> 
      <td align="right"><%= form.label :password_confirmation, "Confirm password" %></td>  
      <td align="left"><%= form.password_field :password_confirmation %></td>   
    </tr>
    <tr>
      <td align="right"><%= form.label :admin_rights, "Admin rights? " %></td>
      <td align="left"><%= check_box_tag 'admin_rights' %></td>
    </tr>
  </table>
  <%= render "shared/error_messages", :target => @user %>
  <br>
  <%= form.submit "Submit" %>
<% end %> 

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'user' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users</h1>
<table class="tables">
  <thead>
    <tr>
      <th>Login</th>
      <th>Count</th>
      <th>Failed</th>
      <th>Last request</th>
      <th>Current</th>
      <th>Last</th>
      <th>Ip Addr</th>
      <th>Last Ip Addr</th>
      <th>Created</th>
      <th>Updated</th>
      <th>Rights</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.login %></td>
        <td><%= user.login_count %></td>
        <td><%= user.failed_login_count %></td>
        <td><%= user.last_request_at %></td>
        <td><%= user.current_login_at %></td>
        <td><%= user.last_login_at %></td>
        <td><%= user.current_login_ip %></td>
        <td><%= user.last_login_ip %></td>
        <td><%= user.created_at %></td>
        <td><%= user.updated_at %></td>
        <% @roles.each do |role| %>
          <% if user.has_role? role.name %>
            <td><%= role.name %></td>
          <% else %>
            <td></td>
          <% end %>
        <% end %>
        <td><%#= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>
<%= render @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>